name: E2E Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/init

      - name: Build CLI
        run: cd turbo && pnpm turbo run build --filter=makita-cli

      - name: Install CLI globally
        run: cd turbo/apps/cli && npm link

      - name: Run E2E Tests
        run: cd e2e && make test
