name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/init

      - name: Lint
        run: |
          cd turbo
          pnpm turbo run lint
          pnpm prettier --check .
