name: Turbo

on:
  push:
    branches:
      - main
  workflow_call:
    outputs:
      artifact-name:
        description: "Name of the uploaded build artifact"
        value: ${{ jobs.build.outputs.artifact-name }}

jobs:
  test:
    runs-on: ubuntu-latest

    # Service containers to run with the job
    services:
      postgres:
        image: postgres:17-alpine
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/init

      - run: npx -y @evilmartians/lefthook run pre-commit --all-files

      - run: cd turbo && pnpm test

  build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      artifact-name: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/init

      - name: Build applications
        run: cd turbo && pnpm build

      - name: Upload build artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: turbo-build-${{ github.run_id }}
          include-hidden-files: true
          path: |
            turbo/apps/*/dist
          retention-days: 7
